Feature with Enumerable Methods
RossielCS/Enumerables pull request #1
Opened 2020-04-15 22:16 UTC by RossielCS

This branch contains the new methods created inside the Enumerable module.
Here I could apply my knowledge about Ruby.

2020-04-16 20:50 UTC, mosesogwo requested changes
**Hi @RossielCS :clap:, you have done a good job here :+1:. Let's take care of the following:**
- **my_count** should return the number of items in an enum.
For example, `[1, 3, 4, 5].my_count` should return `4` instead of `0`
- **my_map** should return an enumerator when no block is given. Currently your method does not handle this, instead it throws an error.
- **my_inject** should take care of cases where a symbol is passed as argument and when a symbol is passed together with an initial accumulator. It should combine the elements of the enum using the operation specified by that symbol.

- **my_inject** returns a wrong result for some random cases. I haven't been able to figure out why yet. Please look at the method again.


_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-17 06:18 UTC, kobiyoyo requested changes
## Hi @RossielCS      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General

- [ ] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method

`p [2,2,2,4,325,2,5,2,12,1,2,12,2,5,6,42,3,2,3,23,2,3,1,32,4,2,4,2,2,4,2,4,2].my_inject(2, :*)` should return `196597446460047360000`

- Combines all elements of enum by applying a binary operation, specified by a block:
`p [2,2,2,4,325,2,5,2,12,1,2,12,2,5,6,42,3,2,3,23,2,3,1,32,4,2,4,2,2,4,2,4,2].inject(4) { |prod, n| prod * n }` should return `393194892920094720000
`





### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-17 23:06 UTC, pelzolga123 requested changes
The project requires changes.

2020-04-17 23:07 UTC, pelzolga123 commented
## Hi Rossiel! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### You did amazing work so far :+1: 
Only one method is still not working correctly:
* [ ] As @mosesogwo pointed previously `my_inject` method is returning wrong results for some random test cases.
`[5,5,7,5,7].my_inject{|a, b| a+b}` - should return 29
Same with next example:
`[5,5,7,5,7].my_inject(:+)` - should return 29

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-04-19 00:20 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @RossielCS  :handshake: 

### Thank you for doing all the changes requested by previous reviewers, the effort you've put into this project shows you are a real team player :soccer: :medal_sports: there are no errors in your code but your my_inject is retrieving wrong answers in some examples so let's fix them :construction: :construction_worker_woman: you can address to the comments I've left in your code bellow :point_down: 

## General
* [ ] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- Your readme file still looks like the template please edit it with your project features and your contact info

### That's it! :raised_hands: 

### Please :pray: do the changes :woman_technologist:  and submit back for a code review when you are done :memo: 

Happy Coding :rocket: 

Any questions? is better to ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-04-19 00:20 UTC, euqueme commented on main.rb
> +  end
- [ ] should have working `my_inject` **(covered by automated tests)** identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

####  my_inject

- [ ] combines all elements of enum by applying a binary operation, specified by a block

```ruby
#Given
array = Array.new(100) { rand(0...100) }
operation = proc { |sum, n| sum + n }

array.my_inject(&operation) == array.inject(&operation) 
```
- Yours is retrieving the wrong answer
![image](https://user-images.githubusercontent.com/52209067/79673924-702af980-819b-11ea-9852-86b318a3208d.png)

- Real inject
![image](https://user-images.githubusercontent.com/52209067/79673936-85a02380-819b-11ea-8e3c-63bc8224c844.png)

- [ ] When a symbol is provided as an argument, my_inject should combine the elements of the enum using that symbol as a named method.
```ruby
#Given
array = Array.new(100) { rand(0...100) }

array.my_inject(:+) == array.inject(:+) 
```
- Yours is retrieving the wrong answer
![image](https://user-images.githubusercontent.com/52209067/79673967-e4fe3380-819b-11ea-8bd9-4c6ef579f74a.png)

- Real inject
![image](https://user-images.githubusercontent.com/52209067/79673977-f6dfd680-819b-11ea-992e-e03e5f7136ac.png)

2020-04-19 00:20 UTC, euqueme commented on main.rb
> +  end
[OPTIONAL]
- [ ] in the specifications of the project in the [Odin project](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks) # 12, you were asked to modify your my_map method to take either a proc or a block. And if both a proc and a block are given, only execute the proc. The real map doesn't have this feature, but you were asked to have it so I strongly recommend working on it

Given 
```ruby
my_proc = Proc.new {|num| num > 10 }
```
Result
```ruby
puts [18, 22, 5, 6] .my_map(my_proc) {|num| num < 10 }  => true true false false
```

2020-04-19 00:20 UTC, euqueme commented on main.rb
> +  end
[OPTIONAL]

- [ ] multiply_els is not an Enumerable method so I strongly recommend to put it in a different module.

2020-04-19 00:20 UTC, euqueme commented on main.rb
> +  end
[OPTIONAL]

I think we could get the block of my_none? from my_any? we should only do something like !my_any? for my_none? to work. For example:
```ruby
  def my_none?(arg = nil, &block)
    !my_any?(arg, &block)
  end
```
To make this work we have to use block.call(element) instead of yield(element) in my_any?

2020-04-20 04:42 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello @RossielCS ,  You have done a great job with this project. :clap:
#### You can go ahead and merge !!!

2020-04-20 14:44 UTC, merged