Added test cases for Enumerable methods
RossielCS/Enumerables pull request #2
Opened 2020-05-06 17:43 UTC by Maclenn77

Hi! @RossielCS and @Maclenn77 here.

We added test cases for the enumerable methods. This worked to find some issues that we didn't see before.

### Tested Methods

- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map
- my_inject

In total, they are 34 test cases.

**Thanks for reviewing!**

2020-05-07 14:24 UTC, shshamim63 requested changes
## Status :traffic_light: Required Changes :tractor: 
___
Hi @Maclenn77 and @RossielCS :wave: 
Awesome job :clap: Almost covered all the test cases, but I can see some space where you need to work a bit. Follow the comment
___
### :spades: Mandatory Changes :spades: 
___
1. Add some tests to the following methods.
- my_all?
- my_any?
- my_none?
2. I cannot see any info into the readme related to test at least how to execute the test. Maybe you can add
To execute the test perform the following command in your terminal.
```bash
rspec spec/main_spec.rb -fdoc #it will provide you well-organized output on your terminal
```
___
### :clubs: Optional Changes :clubs: 
___
You can test your methods by comparing the actual one. Check the sample test to get an idea.
___
##### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-05-07 14:24 UTC, shshamim63 commented on spec/main_spec.rb
> +  end
[Optional]
You can also add a test to check, it is calling the block for each of the items. And as it is derived from an actual method it will be better to compare it with the actual each. Now the question is how can we do that? Check out the sample test below.
```ruby
it 'calls the given block for each of the items in self' do
      each_output = 0
      block = proc { |num| each_output += num }
      array.my_each(&block)
      my_each_output = each_output.dup
      each_output = 0
      array.each(&block)
      expect(my_each_output).to eq(each_output)
end
```

2020-05-07 14:24 UTC, shshamim63 commented on spec/main_spec.rb
> +  end
[Optional]
You can also add a test similar to the given sample test above.

2020-05-07 14:24 UTC, shshamim63 commented on spec/main_spec.rb
> +  end
I cannot see test for the following edge cases of my_all? Please add them
- When a regex is passed as an argument.
- when a value is given other than a class or regex as an argument

2020-05-07 14:24 UTC, shshamim63 commented on spec/main_spec.rb
> +  end
- Add a test case related to regex.

2020-05-07 14:24 UTC, shshamim63 commented on spec/main_spec.rb
> +  end
- Add a test case related to regex as an argument.

2020-05-07 14:24 UTC, shshamim63 commented on spec/main_spec.rb
> +    end
Wow, clever one. :tada:

2020-05-08 16:40 UTC, AdnanAfsari approved these changes
**Status: Approved**

Hello @Maclenn77 @RossielCS ✋ 

Nice work, I think you have made all the changes requested by the previous reviewer 👏 
It's a 👍 from me.

Happy Coding
Adnan Afsari

2020-05-08 16:55 UTC, merged